import {
  brainstem, brainstem1, brainstem2, brainstem3, brainstem4, brainstem5, brainstem6,
  hostage, hostage1, hostage2, hostage3, hostage4, hostage5, hostage6, hostage7, hostage8, hostage9, hostage10, hostage11,
  shapeshooter, shapeshooter1, shapeshooter2, shapeshooter3, shapeshooter4, shapeshooter5, shapeshooter6, shapeshooter7,
  ue5level, ue5level1, ue5level2, ue5level3, ue5level4, ue5level5, ue5level6, ue5level7, ue5level8, ue5level9, ue5level10, ue5level11, ue5level12, ue5level13, ue5level14, ue5level15, ue5level16, ue5level17,
  stenovate
} from "../assets";

const projects = [
  {
    id: "devtechlife",
    summary: "A technology content and developer-tools platform with a React interface, content workflows, and database-backed features.",
    status: "Live website",
    contributions: ["Designed and developed searchable, filterable content and developer-tool listings.", "Implemented authentication, bookmarks, user profiles, access levels, and backend APIs.", "Integrated Sanity publishing workflows, content caching, and scheduled maintenance."],
    decisions: ["Used a headless CMS to separate editorial work from application development.", "Connected OAuth authentication with PostgreSQL-backed application features."],
    statusNote: "Public website with searchable content, developer-tool listings, and account features.",
    category: "web",
    name: "DevTechLife",
    description:
      "A full-stack platform for discovering developer tools and practical technical guides. I built the Next.js, React, and TypeScript application with a Sanity content workflow and PostgreSQL data layer. The site includes searchable tool and article listings, filters, pagination, OAuth sign-in, saved bookmarks, and role-based access. My work also covers backend APIs, caching, structured metadata, and content automation.",
    tags: [
      { name: "next.js", color: "blue-text-gradient" },
      { name: "react", color: "green-text-gradient" },
      { name: "typescript", color: "pink-text-gradient" },
      { name: "sanity", color: "orange-text-gradient" },
      { name: "postgresql", color: "purple-text-gradient" },
    ],
    image: "/project-media/devtechlife-home-dark.jpg",
    image1: "/project-media/devtechlife-tools-dark.jpg",
    image2: "/project-media/devtechlife-articles-dark.jpg",
    image3: "/project-media/devtechlife-tool-dark.jpg",
    image4: "/project-media/devtechlife-article-dark.jpg",
    image5: "/project-media/devtechlife-home-content-dark.jpg",
    live_url: "https://devtechlife.com",
    source_code_link: "None",
  },
  {
    id: "leaptalkavatar",
    summary: "An application layer coordinating language-model responses, speech synthesis, and avatar-video generation using existing models.",
    status: "Local personal application",
    contributions: ["Implemented conversation state, API orchestration, and error handling.", "Coordinated speech and avatar output with timing and GPU resource management.", "Added application tests and validation workflows."],
    decisions: ["Integrated existing models with custom application and workflow logic.", "Managed resource lifecycles to support sequential local generation."],
    statusNote: "Local talking-avatar application. The gallery includes existing demo output and a UI capture; the AI models and LeapTalk renderer are upstream components.",
    category: "ai-tools",
    name: "LeapTalkAvatar",
    description:
      "A local talking-avatar application that turns typed messages into spoken, animated replies. I built the FastAPI application and orchestration around local language models, speech synthesis, and the upstream LeapTalk renderer. The application manages conversation state, portraits, character sheets, optional continuity between replies, and GPU resource handoff. Its media assembly combines video with a continuous audio track to prevent drift from separately encoded chunks.",
    tags: [
      { name: "python", color: "blue-text-gradient" },
      { name: "fastapi", color: "green-text-gradient" },
      { name: "ollama", color: "pink-text-gradient" },
      { name: "tts", color: "orange-text-gradient" },
      { name: "ffmpeg", color: "purple-text-gradient" },
    ],
    image: "/project-media/leaptalkavatar-frame.png",
    image1: "/project-media/leaptalkavatar-ui.png",
    image2: "/project-media/leaptalkavatar-pipeline.svg",
    image3: "/project-media/leaptalkavatar-controls.svg",
    demo_video: "/project-media/leaptalkavatar-demo.mp4",
    media_note: "Existing local demo output and UI capture, plus implementation diagrams. The AI models and LeapTalk renderer are upstream components; my work is the application and integration layer.",
    source_code_link: "None",
  },
  {
    id: "catchat",
    summary: "A configurable voice-chat pipeline connecting speech recognition, language models, and speech synthesis through Pipecat and WebRTC.",
    status: "Local personal application",
    contributions: ["Connected local and cloud STT, LLM, and TTS providers.", "Implemented a custom HTTP adapter for local speech-generation services.", "Added provider configuration and validation."],
    decisions: ["Built around existing Pipecat components and provider APIs rather than training original models.", "Supported interchangeable providers for local and cloud workflows."],
    statusNote: "Local voice-chat prototype. The gallery contains implementation diagrams; a public live demo is not hosted.",
    category: "ai-tools",
    name: "CatChat",
    description:
      "A browser-connected voice chatbot prototype built with Python and Pipecat. I integrated WebRTC audio with configurable speech recognition, language model, and speech synthesis providers, including local Whisper, Ollama, and Piper options. A custom HTTP speech adapter maps request fields and streams audio from additional local TTS services into the pipeline, with configuration validation and error handling.",
    tags: [
      { name: "python", color: "blue-text-gradient" },
      { name: "pipecat", color: "green-text-gradient" },
      { name: "webrtc", color: "pink-text-gradient" },
      { name: "whisper", color: "orange-text-gradient" },
      { name: "ollama", color: "purple-text-gradient" },
    ],
    image: "/project-media/catchat-pipeline.svg",
    image_fit: "contain",
    image1: "/project-media/catchat-providers.svg",
    image2: "/project-media/catchat-adapter.svg",
    media_note: "Architecture diagrams based on the implementation. This prototype runs locally; a public live demo is not hosted.",
    source_code_link: "None",
  },
  {
    id: "brainstem",
    summary: "A Godot platformer prototype combining gameplay development, asset integration, and a custom-composed soundtrack.",
    status: "Student project / prototype",
    contributions: ["A Godot platformer prototype combining gameplay development, asset integration, and a custom-composed soundtrack."],
    decisions: ["Combined existing engines or frameworks with custom application logic and integrated assets."],
    statusNote: "Student project / prototype, documented through screenshots and available demonstrations.",
    category: "games",
    name: "Brainstem (prototype)",
    description:
      "<i>Brainstem</i> is a 2D side-scrolling action-adventure platformer created in Godot 4.2 using the GDScript programming language. The game combines original assets, including a custom-composed soundtrack for level two, with meticulously tailored graphics and audio sourced from Twitch.io and Pixabay.com, ensuring a cohesive and immersive player experience. Built to showcase fluid mechanics and dynamic environments, <i>Brainstem</i> reflects a strong foundation in game design, asset integration, and gameplay refinement.",
    tags: [
      { name: "godot", color: "blue-text-gradient" },
      { name: "aseprite", color: "green-text-gradient" },
      { name: "photoshop", color: "pink-text-gradient" },
      { name: "cakewalk", color: "orange-text-gradient" },
      { name: "audacity", color: "purple-text-gradient" },
    ],
    image: brainstem,
    image1: brainstem1,
    image2: brainstem2,
    image3: brainstem3,
    image4: brainstem4,
    image5: brainstem5,
    image6: brainstem6,
    video: "https://www.youtube.com/embed/dch-rlHtmAg?si=akbYlHMwsKHOUw_t",
    video_title: "Brainstem Gameplay Demo",
    source_code_link: "https://github.com/snl60/Brainstem",
  },
  {
    id: "hostage",
    summary: "An Unreal Engine level integrating Blueprint interactions, combat, and enemy AI using Behavior Trees and Blackboards.",
    status: "Student project / prototype",
    contributions: ["An Unreal Engine level integrating Blueprint interactions, combat, and enemy AI using Behavior Trees and Blackboards."],
    decisions: ["Combined existing engines or frameworks with custom application logic and integrated assets."],
    statusNote: "Student project / prototype, documented through screenshots and available demonstrations.",
    category: "games",
    name: "Hostage Negotiation",
    description:
      "A custom single-player level in Unreal Engine 5, showcasing my skill in integrating environment design with engaging, combat-focused gameplay. Using Unreal's Landscape and Foliage systems, I developed a visually immersive terrain. The Blueprint system enabled fluid player interactions and combat mechanics, while custom enemy AIâ€”built with Behavior Trees and Blackboardsâ€”provides challenging, adaptive gameplay. This project highlights my skill in uniting design elements and technical systems to create a seamless, interactive experience.",
    tags: [
      { name: "unreal engine", color: "blue-text-gradient" },
      { name: "mixamo", color: "green-text-gradient" },
      { name: "blender", color: "pink-text-gradient" },
    ],
    image: hostage,
    image1: hostage1,
    image2: hostage2,
    image3: hostage3,
    image4: hostage4,
    image5: hostage5,
    image6: hostage6,
    image7: hostage7,
    image8: hostage8,
    image9: hostage9,
    image10: hostage10,
    image11: hostage11,
    source_code_link: "None",
  },
  {
    id: "shape-shooter",
    summary: "An Unreal Engine C++ project implementing player controls, projectile combat, and enemy behaviors.",
    status: "Student project / prototype",
    contributions: ["An Unreal Engine C++ project implementing player controls, projectile combat, and enemy behaviors."],
    decisions: ["Combined existing engines or frameworks with custom application logic and integrated assets."],
    statusNote: "Student project / prototype, documented through screenshots and available demonstrations.",
    category: "games",
    name: "Shape Shooter",
    description:
      "Shape Shooter is a fast-paced top-down shooting game where players control a cone that fires projectiles to fend off waves of enemy shapes. Each enemy type has unique behaviors, creating dynamic challenges as players advance through increasingly intense waves. With responsive controls and strategic gameplay, Shape Shooter combines simplicity with depth for an engaging, action-packed experience.",
    tags: [
      { name: "unreal engine", color: "blue-text-gradient" },
      { name: "c++", color: "green-text-gradient" },
      { name: "visual studio", color: "pink-text-gradient" },
    ],
    image: shapeshooter,
    image1: shapeshooter1,
    image2: shapeshooter2,
    image3: shapeshooter3,
    image4: shapeshooter4,
    image5: shapeshooter5,
    image6: shapeshooter6,
    image7: shapeshooter7,
    source_code_link: "https://github.com/snl60/ShapeShooter",
  },
  {
    id: "ue5level",
    summary: "An Unreal Engine level combining terrain, enemy AI, progression, UI, and audiovisual feedback.",
    status: "Student project / prototype",
    contributions: ["An Unreal Engine level combining terrain, enemy AI, progression, UI, and audiovisual feedback."],
    decisions: ["Combined existing engines or frameworks with custom application logic and integrated assets."],
    statusNote: "Student project / prototype, documented through screenshots and available demonstrations.",
    category: "games",
    name: "Unreal Engine 5 Level",
    description:
      "This Unreal Engine 5 level highlights my skills in environment design, using Landscape and Foliage tools for immersive terrain and Blueprint systems for gameplay. Players engage with enemy bear AI, unlock doors by leveling up, and reach a win state by stepping on a pressure plate. The level includes custom UI elements like a HUD, pause, and main menus, along with audio cues, particle effects, and a cinematic flythrough at the start. This project demonstrates my ability to integrate design, gameplay, and UI for a cohesive, interactive experience.",
    tags: [
      { name: "unreal engine", color: "blue-text-gradient" },
    ],
    image: ue5level,
    image1: ue5level1,
    image2: ue5level2,
    image3: ue5level3,
    image4: ue5level4,
    image5: ue5level5,
    image6: ue5level6,
    image7: ue5level7,
    image8: ue5level8,
    image9: ue5level9,
    image10: ue5level10,
    image11: ue5level11,
    image12: ue5level12,
    image13: ue5level13,
    image14: ue5level14,
    image15: ue5level15,
    image16: ue5level16,
    image17: ue5level17,
    source_code_link: "None",
  },
  {
    id: "stenovate",
    summary: "A Python desktop interface around OpenAI Whisper for file transcription and user-selected output locations.",
    status: "Personal project",
    contributions: ["A Python desktop interface around OpenAI Whisper for file transcription and user-selected output locations."],
    decisions: ["Combined existing engines or frameworks with custom application logic and integrated assets."],
    statusNote: "Open-source desktop transcription application built around OpenAI Whisper.",
    category: "ai-tools",
    name: "Stenovate Speech-to-Text",
    description:
      "Stenovate is an open-source speech-to-text application designed for fast, accurate transcription across multiple languages. Built on OpenAI's powerful Whisper model, Stenovate enables users to convert audio files into text with exceptional precision, ideal for professionals and multilingual environments. With a user-friendly interface, users can easily select audio files for transcription, customize save locations, and manage transcriptions seamlessly. Stenovate also includes custom file management and user-defined save directories, making it a reliable, versatile tool for accurate speech transcription in various workflows.",
    tags: [
      { name: "python", color: "blue-text-gradient" },
      { name: "openai whisper", color: "green-text-gradient" },
      { name: "tkinter", color: "pink-text-gradient" },
      { name: "pytorch", color: "orange-text-gradient" },
      { name: "open source", color: "purple-text-gradient" },
    ],
    image: stenovate,
    video: "https://www.youtube.com/embed/BTlptlhtD-8?si=FK8xQxG5mmZN4Yxc",
    video_title: "Stenovate: Powerful Open-Source Speech-to-Text App for Accurate Transcription",
    source_code_link: "https://github.com/snl60/stenovate",
  },
];

export default projects;
